namespace SmartyStreets.USEnrichmentApi.ResultTypes.Property
{
    public class Attributes
    {
        [JsonProperty("1st_floor_sqft")]
        public string first_floor_sqft { get; set; }

        [JsonProperty("2nd_floor_sqft")]
        public string second_floor_sqft { get; set; }
        public string acres { get; set; }
        public string air_conditioner { get; set; }
        public string arbor_pergola { get; set; }
        public string assessed_improvement_percent { get; set; }
        public string assessed_improvement_value { get; set; }
        public string assessed_land_value { get; set; }
        public string assessed_value { get; set; }
        public string assessor_last_update { get; set; }
        public string assessor_taxroll_update { get; set; }
        public string attic_area { get; set; }
        public string attic_flag { get; set; }
        public string balcony { get; set; }
        public string balcony_area { get; set; }
        public string basement_sqft { get; set; }
        public string basement_sqft_finished { get; set; }
        public string basement_sqft_unfinished { get; set; }
        public string bath_house { get; set; }
        public string bath_house_sqft { get; set; }
        public string bathrooms_partial { get; set; }
        public string bathrooms_total { get; set; }
        public string bedrooms { get; set; }
        public string block1 { get; set; }
        public string block2 { get; set; }
        public string boat_access { get; set; }
        public string boat_house { get; set; }
        public string boat_house_sqft { get; set; }
        public string boat_lift { get; set; }
        public string bonus_room { get; set; }
        public string breakfast_nook { get; set; }
        public string breezeway { get; set; }
        public string building_definition_code { get; set; }
        public string building_sqft { get; set; }
        public string cabin { get; set; }
        public string cabin_sqft { get; set; }
        public string canopy { get; set; }
        public string canopy_sqft { get; set; }
        public string carport { get; set; }
        public string carport_sqft { get; set; }
        public string cbsa_code { get; set; }
        public string cbsa_name { get; set; }
        public string cellar { get; set; }
        public string census_block { get; set; }
        public string census_block_group { get; set; }
        public string census_fips_place_code { get; set; }
        public string census_tract { get; set; }
        public string central_vacuum { get; set; }
        public string code_title_company { get; set; }
        public string combined_statistical_area { get; set; }
        public string community_rec { get; set; }
        public string company_flag { get; set; }
        public string congressional_district { get; set; }
        public string construction_type { get; set; }
        public string contact_city { get; set; }
        public string contact_crrt { get; set; }
        public string contact_full_address { get; set; }
        public string contact_house_number { get; set; }
        public string contact_mail_info_format { get; set; }
        public string contact_mail_info_privacy { get; set; }
        public string contact_mailing_county { get; set; }
        public string contact_mailing_fips { get; set; }
        public string contact_post_direction { get; set; }
        public string contact_pre_direction { get; set; }
        public string contact_state { get; set; }
        public string contact_street_name { get; set; }
        public string contact_suffix { get; set; }
        public string contact_unit_designator { get; set; }
        public string contact_value { get; set; }
        public string contact_zip { get; set; }
        public string contact_zip4 { get; set; }
        public string courtyard { get; set; }
        public string courtyard_area { get; set; }
        public string deck { get; set; }
        public string deck_area { get; set; }
        public string deed_document_book { get; set; }
        public string deed_document_number { get; set; }
        public string deed_document_page { get; set; }
        public string deed_owner_first_name { get; set; }
        public string deed_owner_first_name2 { get; set; }
        public string deed_owner_first_name3 { get; set; }
        public string deed_owner_first_name4 { get; set; }
        public string deed_owner_full_name { get; set; }
        public string deed_owner_full_name2 { get; set; }
        public string deed_owner_full_name3 { get; set; }
        public string deed_owner_full_name4 { get; set; }
        public string deed_owner_last_name { get; set; }
        public string deed_owner_last_name2 { get; set; }
        public string deed_owner_last_name3 { get; set; }
        public string deed_owner_last_name4 { get; set; }
        public string deed_owner_middle_name { get; set; }
        public string deed_owner_middle_name2 { get; set; }
        public string deed_owner_middle_name3 { get; set; }
        public string deed_owner_middle_name4 { get; set; }
        public string deed_owner_suffix { get; set; }
        public string deed_owner_suffix2 { get; set; }
        public string deed_owner_suffix3 { get; set; }
        public string deed_owner_suffix4 { get; set; }
        public string deed_sale_date { get; set; }
        public string deed_sale_price { get; set; }
        public string deed_transaction_id { get; set; }
        public string depth_linear_footage { get; set; }
        public string disabled_tax_exemption { get; set; }
        public string document_type_description { get; set; }
        public string driveway_sqft { get; set; }
        public string driveway_type { get; set; }
        public string effective_year_built { get; set; }
        public string elevation_feet { get; set; }
        public string elevator { get; set; }
        public string equestrian_arena { get; set; }
        public string escalator { get; set; }
        public string exercise_room { get; set; }
        public string exterior_walls { get; set; }
        public string family_room { get; set; }
        public string fence { get; set; }
        public string fence_area { get; set; }
        public string fips_code { get; set; }
        public string fire_resistance_code { get; set; }
        public string fire_sprinklers_flag { get; set; }
        public string fireplace { get; set; }
        public string fireplace_number { get; set; }
        public string first_name { get; set; }
        public string first_name_2 { get; set; }
        public string first_name_3 { get; set; }
        public string first_name_4 { get; set; }
        public string flooring { get; set; }
        public string foundation { get; set; }
        public string game_room { get; set; }
        public string garage { get; set; }
        public string garage_sqft { get; set; }
        public string gazebo { get; set; }
        public string gazebo_sqft { get; set; }
        public string golf_course { get; set; }
        public string grainery { get; set; }
        public string grainery_sqft { get; set; }
        public string great_room { get; set; }
        public string greenhouse { get; set; }
        public string greenhouse_sqft { get; set; }
        public string gross_sqft { get; set; }
        public string guesthouse { get; set; }
        public string guesthouse_sqft { get; set; }
        public string handicap_accessibility { get; set; }
        public string heat { get; set; }
        public string heat_fuel_type { get; set; }
        public string hobby_room { get; set; }
        public string homeowner_tax_exemption { get; set; }
        public string instrument_date { get; set; }
        public string intercom_system { get; set; }
        public string interest_rate_type_2 { get; set; }
        public string interior_structure { get; set; }
        public string kennel { get; set; }
        public string kennel_sqft { get; set; }
        public string land_use_code { get; set; }
        public string land_use_group { get; set; }
        public string land_use_standard { get; set; }
        public string last_name { get; set; }
        public string last_name_2 { get; set; }
        public string last_name_3 { get; set; }
        public string last_name_4 { get; set; }
        public string latitude { get; set; }
        public string laundry { get; set; }
        public string lean_to { get; set; }
        public string lean_to_sqft { get; set; }
        public string legal_description { get; set; }
        public string legal_unit { get; set; }
        public string lender_address { get; set; }
        public string lender_address_2 { get; set; }
        public string lender_city { get; set; }
        public string lender_city_2 { get; set; }
        public string lender_code_2 { get; set; }
        public string lender_first_name { get; set; }
        public string lender_first_name_2 { get; set; }
        public string lender_last_name { get; set; }
        public string lender_last_name_2 { get; set; }
        public string lender_name { get; set; }
        public string lender_name_2 { get; set; }
        public string lender_seller_carry_back { get; set; }
        public string lender_seller_carry_back_2 { get; set; }
        public string lender_state { get; set; }
        public string lender_state_2 { get; set; }
        public string lender_zip { get; set; }
        public string lender_zip_2 { get; set; }
        public string lender_zip_extended { get; set; }
        public string lender_zip_extended_2 { get; set; }
        public string loading_platform { get; set; }
        public string loading_platform_sqft { get; set; }
        public string longitude { get; set; }
        public string lot_1 { get; set; }
        public string lot_2 { get; set; }
        public string lot_3 { get; set; }
        public string lot_sqft { get; set; }
        public string market_improvement_percent { get; set; }
        public string market_improvement_value { get; set; }
        public string market_land_value { get; set; }
        public string market_value_year { get; set; }
        public string match_type { get; set; }
        public string media_room { get; set; }
        public string metro_division { get; set; }
        public string middle_name { get; set; }
        public string middle_name_2 { get; set; }
        public string middle_name_3 { get; set; }
        public string middle_name_4 { get; set; }
        public string milkhouse { get; set; }
        public string milkhouse_sqft { get; set; }
        public string minor_civil_division_code { get; set; }
        public string minor_civil_division_name { get; set; }
        public string mobile_home_hookup { get; set; }
        public string mortgage_amount { get; set; }
        public string mortgage_amount_2 { get; set; }
        public string mortgage_due_date { get; set; }
        public string mortgage_due_date_2 { get; set; }
        public string mortgage_interest_rate { get; set; }
        public string mortgage_interest_rate_type { get; set; }
        public string mortgage_lender_code { get; set; }
        public string mortgage_rate_2 { get; set; }
        public string mortgage_recording_date { get; set; }
        public string mortgage_recording_date_2 { get; set; }
        public string mortgage_term { get; set; }
        public string mortgage_term_2 { get; set; }
        public string mortgage_term_type { get; set; }
        public string mortgage_term_type_2 { get; set; }
        public string mortgage_type { get; set; }
        public string mortgage_type_2 { get; set; }
        public string msa_code { get; set; }
        public string msa_name { get; set; }
        public string mud_room { get; set; }
        public string multi_parcel_flag { get; set; }
        public string name_title_company { get; set; }
        public string neighborhood_code { get; set; }
        public string number_of_buildings { get; set; }
        public string office { get; set; }
        public string office_sqft { get; set; }
        public string other_tax_exemption { get; set; }
        public string outdoor_kitchen_fireplace { get; set; }
        public string overhead_door { get; set; }
        public string owner_full_name { get; set; }
        public string owner_full_name_2 { get; set; }
        public string owner_full_name_3 { get; set; }
        public string owner_full_name_4 { get; set; }
        public string owner_occupancy_status { get; set; }
        public string ownership_transfer_date { get; set; }
        public string ownership_transfer_doc_number { get; set; }
        public string ownership_transfer_transaction_id { get; set; }
        public string ownership_type { get; set; }
        public string ownership_type_2 { get; set; }
        public string ownership_vesting_relation_code { get; set; }
        public string parcel_account_number { get; set; }
        public string parcel_map_book { get; set; }
        public string parcel_map_page { get; set; }
        public string parcel_number_alternate { get; set; }
        public string parcel_number_formatted { get; set; }
        public string parcel_number_previous { get; set; }
        public string parcel_number_year_added { get; set; }
        public string parcel_number_year_change { get; set; }
        public string parcel_raw_number { get; set; }
        public string parcel_shell_record { get; set; }
        public string parking_spaces { get; set; }
        public string patio_area { get; set; }
        public string phase_name { get; set; }
        public string plumbing_fixtures_count { get; set; }
        public string pole_struct { get; set; }
        public string pole_struct_sqft { get; set; }
        public string pond { get; set; }
        public string pool { get; set; }
        public string pool_area { get; set; }
        public string poolhouse { get; set; }
        public string poolhouse_sqft { get; set; }
        public string porch { get; set; }
        public string porch_area { get; set; }
        public string poultry_house { get; set; }
        public string poultry_house_sqft { get; set; }
        public string previous_assessed_value { get; set; }
        public string prior_sale_amount { get; set; }
        public string prior_sale_date { get; set; }
        public string property_address_carrier_route_code { get; set; }
        public string property_address_city { get; set; }
        public string property_address_full { get; set; }
        public string property_address_house_number { get; set; }
        public string property_address_post_direction { get; set; }
        public string property_address_pre_direction { get; set; }
        public string property_address_state { get; set; }
        public string property_address_street_name { get; set; }
        public string property_address_street_suffix { get; set; }
        public string property_address_unit_designator { get; set; }
        public string property_address_unit_value { get; set; }
        public string property_address_zip_4 { get; set; }
        public string property_address_zipcode { get; set; }
        public string publication_date { get; set; }
        public string quarter { get; set; }
        public string quarter_quarter { get; set; }
        public string quonset { get; set; }
        public string quonset_sqft { get; set; }
        public string range { get; set; }
        public string recording_date { get; set; }
        public string roof_cover { get; set; }
        public string roof_frame { get; set; }
        public string rooms { get; set; }
        public string rv_parking { get; set; }
        public string safe_room { get; set; }
        public string sale_amount { get; set; }
        public string sale_date { get; set; }
        public string sauna { get; set; }
        public string section { get; set; }
        public string security_alarm { get; set; }
        public string senior_tax_exemption { get; set; }
        public string sewer_type { get; set; }
        public string shed { get; set; }
        public string shed_sqft { get; set; }
        public string silo { get; set; }
        public string silo_sqft { get; set; }
        public string sitting_room { get; set; }
        public string situs_county { get; set; }
        public string situs_state { get; set; }
        public string sound_system { get; set; }
        public string sports_court { get; set; }
        public string sprinklers { get; set; }
        public string stable { get; set; }
        public string stable_sqft { get; set; }
        public string storage_building { get; set; }
        public string storage_building_sqft { get; set; }
        public string stories_number { get; set; }
        public string storm_shelter { get; set; }
        public string storm_shutter { get; set; }
        public string structure_style { get; set; }
        public string study { get; set; }
        public string subdivision { get; set; }
        public string suffix { get; set; }
        public string suffix_2 { get; set; }
        public string suffix_3 { get; set; }
        public string suffix_4 { get; set; }
        public string sunroom { get; set; }
        public string tax_assess_year { get; set; }
        public string tax_billed_amount { get; set; }
        public string tax_delinquent_year { get; set; }
        public string tax_fiscal_year { get; set; }
        public string tax_jurisdiction { get; set; }
        public string tax_rate_area { get; set; }
        public string tennis_court { get; set; }
        public string topography_code { get; set; }
        public string total_market_value { get; set; }
        public string township { get; set; }
        public string tract_number { get; set; }
        public string transfer_amount { get; set; }
        public string trust_description { get; set; }
        public string unit_count { get; set; }
        public string upper_floors_sqft { get; set; }
        public string utility { get; set; }
        public string utility_building { get; set; }
        public string utility_building_sqft { get; set; }
        public string utility_sqft { get; set; }
        public string veteran_tax_exemption { get; set; }
        public string view_description { get; set; }
        public string water_feature { get; set; }
        public string water_service_type { get; set; }
        public string wet_bar { get; set; }
        public string widow_tax_exemption { get; set; }
        public string width_linear_footage { get; set; }
        public string wine_cellar { get; set; }
        public string year_built { get; set; }
        public string zoning { get; set; }
    }
}