name: Publish NuGet Package

on:
  push:
    tags:
      - '**'

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x

      - name: Publish
        run: NUGET_KEY=${{ secrets.NUGET_API_KEY }} VERSION=${GITHUB_REF#refs/tags/} make release
