name: Reusable Test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x', '9.0.x', '10.0.x']
    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v5
        id: stepid
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Pin SDK version
        run: echo '{"sdk":{"version":"${{ steps.stepid.outputs.dotnet-version }}"}}' > ./global.json

      - name: Build
        run: make compile

      - name: Test
        run: make test
